train:
  seed: 42
  task: 'classification_indices'
  epochs: 4
  batch_size: 64
  num_workers: 8
model:
  pretrained_lm_name: 'distilbert-base-uncased'
  task_params:
    classification_answerable:
      downstream_head_in_size: 768
      downstream_head_out_size: 2
    classification_indices:
      downstream_head_in_size: 768
      downstream_head_out_size: 2
  lm_dropout_prob: 0.1
optimizer:
  b1: 0.9
  b2: 0.999
  eps: 1e-8
  learning_rate: 3e-5
